### ISSUE TITLE
docker file directory

### ISSUE THREAD

**Issue by ehsanhrz** [parswebserver/runflare-cli#1]
if we create a docker item on runflare we have to put our docker file on the root directory and this will not be a big problem if someone has only one docker file but if we want to deploy a project with multiple dockerfile we will encounter problems. so adding a new feature that allows users to choose docker file and upload the project will be ideal to us. if this feature is developable i can help to do it.

**Comment by mhmdhoseinzade** [comment]
Hello @ehsanhrz 
I wanted to extend my heartfelt thanks for taking the time to share your idea on Runflare Cli. Your idea is immensely valued, and we deeply appreciate your commitment to improving our project.
We assumed that the production docker name must be **Dockerfile** and the development docker file and others must have different names. For testing purposes, you have to create another item and test your docker file there.
